version: 2

project_name: curlex

env:
  - GO111MODULE=on
  - GOPROXY=https://proxy.golang.org
  - CGO_ENABLED=0

before:
  hooks:
    - make clean
    - go mod tidy

builds:
  - id: curlex
    binary: curlex
    main: cmd/curlex/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - '-X github.com/jonhadfield/curlex/helpers.Version={{ .Version }}_{{ .Date }}_UTC'
      - '-X github.com/jonhadfield/curlex/helpers.SemVer={{ .Tag }}'

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - license*
      - readme*
      - changelog*
      - none*

universal_binaries:
  - replace: false

checksum:
  name_template: checksums.txt

release:
  github:
    owner: jonhadfield
    name: curlex
  prerelease: auto
  name_template: "{{ .Tag }}"

changelog:
  sort: asc
  filters:
    exclude:
      - README*
      - test
      - ignore

brews:
  - name: curlex
    homepage: https://github.com/jonhadfield/curlex
    description: >
      A lightweight CLI tool for testing HTTP endpoints with curl-style commands and structured assertions.
    repository:
      owner: jonhadfield
      name: homebrew-curlex
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    skip_upload: auto
    install: |
      bin.install "curlex"
    test: |
      system "#{bin}/curlex", "--version"

announce:
  skip: true
